# Generated by Django 2.2.8 on 2021-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210203_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_text',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('B', 'Bestseller'), ('C', 'Coming Soon')], max_length=1, null=True),
        ),
    ]
